INSERT INTO feedback (source, author, text, created_at, sentiment, urgency, themes, processed) VALUES
-- Discord (6)
('discord', 'devuser42',    'Workers seems to randomly drop connections after about 30 seconds of inactivity. Happening in production for us. Is this a known issue?',                                                                       '2026-04-24T09:12:00Z', 'negative', 8,  '["Workers","Reliability","Production Issue"]',           1),
('discord', 'cloudbuilder', 'Just deployed my first Workers site using D1 and it was honestly way easier than expected. The wrangler CLI is super smooth.',                                                                                 '2026-04-24T14:30:00Z', 'positive', 2,  '["Workers","D1","Developer Experience"]',                1),
('discord', 'mlhacker99',   'Anyone else getting rate limited by Workers AI? Trying to run llama-3 for a batch job and hitting limits constantly.',                                                                                         '2026-04-25T11:05:00Z', 'negative', 7,  '["Workers AI","Rate Limits","Batch Processing"]',        1),
('discord', 'cf_watcher',   'The new Workflows feature is interesting but the docs are really sparse. Would love more examples of real-world use cases.',                                                                                   '2026-04-25T16:44:00Z', 'neutral',  4,  '["Workflows","Documentation"]',                          1),
('discord', 'tsdev_',       'Wrangler types command does not update after adding a new KV binding. Have to delete and regenerate manually each time.',                                                                                      '2026-04-26T08:20:00Z', 'negative', 5,  '["Wrangler","TypeScript","Developer Experience"]',       1),
('discord', 'edge_enjoyer', 'R2 plus Workers combo is absolutely incredible for media serving. Sub-10ms globally. Cloudflare engineering is impressive.',                                                                                   '2026-04-26T19:55:00Z', 'positive', 1,  '["R2","Performance","Workers"]',                          1),

-- GitHub Issues (6)
('github',  'reporter_x',   'Bug: D1 returns null for LEFT JOIN when right table has no matching row instead of the expected null column values. Reproducible with simple schema.',                                                         '2026-04-24T10:00:00Z', 'negative', 9,  '["D1","SQL","Bug"]',                                     1),
('github',  'workflow_fan', 'Feature Request: Add support for scheduled Workflows with cron triggers. Having to manually trigger via fetch defeats the durable execution story.',                                                           '2026-04-25T13:15:00Z', 'neutral',  6,  '["Workflows","Cron","Feature Request"]',                 1),
('github',  'wrangler_dev', 'wrangler dev --remote fails with 401 when using service bindings across accounts. Works fine with --local flag.',                                                                                              '2026-04-25T17:30:00Z', 'negative', 7,  '["Wrangler","Service Bindings","Authentication"]',       1),
('github',  'llm_tester',   'Workers AI llama-3.1-8b-instruct context window appears capped at 2048 tokens despite documentation stating 8192.',                                                                                           '2026-04-26T09:40:00Z', 'negative', 8,  '["Workers AI","Documentation","LLM Context"]',           1),
('github',  'd1_user',      'Request: Improve error messages from D1 migrations. Currently shows generic SQL error without line numbers, very hard to debug.',                                                                              '2026-04-27T14:00:00Z', 'neutral',  5,  '["D1","Developer Experience","Error Messages"]',         1),
('github',  'kv_pager',     'KV list() with prefix does not return keys in alphabetical order consistently. This breaks pagination logic in our app.',                                                                                      '2026-04-28T10:25:00Z', 'negative', 6,  '["KV","Bug","Pagination"]',                              1),

-- Twitter/X (6)
('twitter', '@speedcheck',  'wrangler deploy took 4 minutes today. Usually under 30 seconds. Is something wrong with the deploy pipeline?',                                                                                                '2026-04-24T18:02:00Z', 'negative', 7,  '["Wrangler","Deployment","Performance"]',                1),
('twitter', '@costsavings', 'Moved image CDN to R2 plus Workers last week. Bill went from $800/mo to $40/mo. No other changes. Still in shock.',                                                                                           '2026-04-25T09:11:00Z', 'positive', 1,  '["R2","Pricing","CDN"]',                                 1),
('twitter', '@observ_dev',  'Please add a proper dashboard for Workers AI usage. No way to know how many tokens are burning until the monthly bill hits.',                                                                                  '2026-04-26T12:33:00Z', 'negative', 6,  '["Workers AI","Dashboard","Observability"]',             1),
('twitter', '@pipeliner',   'Every time I try to use D1 inside a Workflow step it times out. The CPU limit is way too restrictive for ML pipelines.',                                                                                       '2026-04-27T08:45:00Z', 'negative', 8,  '["D1","Workflows","CPU Limit"]',                         1),
('twitter', '@edgefan',     'Impressed by Workers cold start times. Under 1ms vs AWS Lambda 200ms plus for the same workload. Night and day difference.',                                                                                   '2026-04-28T15:20:00Z', 'positive', 1,  '["Workers","Performance","Cold Start"]',                 1),
('twitter', '@retrylogic',  'AI Gateway needs better retry logic. Failed requests return 404 instead of falling back to the model. No graceful degradation.',                                                                               '2026-04-29T11:10:00Z', 'negative', 6,  '["AI Gateway","Reliability","Error Handling"]',          1),

-- Support Tickets (6)
('support', 'ticket_8821',  'Intermittent 500 errors from Workers deployment. Logs show Worker exceeded CPU time limit but worker only does simple JSON parsing. Blocking production.',                                                     '2026-04-23T07:30:00Z', 'negative', 10, '["Workers","CPU Limit","Production Issue"]',             1),
('support', 'ticket_8834',  'Cannot find how to set environment variables per environment (staging vs production) in the new wrangler.jsonc format. Documentation only covers old wrangler.toml.',                                          '2026-04-24T11:00:00Z', 'neutral',  5,  '["Wrangler","Documentation","Environment Variables"]',  1),
('support', 'ticket_8850',  'Billing issue: charged for Workers AI tokens that were never returned due to timeout errors. Requesting credit for approximately 50000 tokens.',                                                               '2026-04-25T14:20:00Z', 'negative', 7,  '["Workers AI","Billing","Reliability"]',                 1),
('support', 'ticket_8861',  'D1 migrations failing on production but succeeding in dev. Error: SQLITE_CONSTRAINT_UNIQUE. Data should be clean. No way to inspect current migration state.',                                                 '2026-04-26T09:50:00Z', 'negative', 9,  '["D1","Migrations","Production Issue"]',                 1),
('support', 'ticket_8877',  'Dashboard asks to add a site before creating Workers. We only want serverless functions without a domain. Navigation is confusing for pure serverless developers.',                                            '2026-04-27T16:30:00Z', 'neutral',  4,  '["Dashboard","Onboarding","Developer Experience"]',     1),
('support', 'ticket_8892',  'Workers Secrets UI only allows setting one secret at a time. Please add bulk import from a .env file for teams managing many secrets.',                                                                        '2026-04-28T10:05:00Z', 'neutral',  5,  '["Workers","Secrets","Developer Experience"]',          1),

-- Community Forum (6)
('forum',   'forum_pm_guy', 'Best practices for handling Workers AI rate limits in production? Building a support bot and hitting limits during peak hours. Looking for patterns others have used.',                                         '2026-04-24T13:00:00Z', 'neutral',  5,  '["Workers AI","Rate Limits","Best Practices"]',          1),
('forum',   'workflow_n00b','Anyone successfully passed D1 results between Workflow steps? Getting serialization errors. Passing the D1 result object directly seems to cause silent failures.',                                            '2026-04-25T10:30:00Z', 'negative', 6,  '["D1","Workflows","Serialization"]',                     1),
('forum',   'migration_guy','Sharing experience migrating from Vercel to Cloudflare Workers. Deployment is faster, pricing is better, but DX for full-stack apps still has rough edges vs Next.js. Worth it overall.',                    '2026-04-26T17:15:00Z', 'neutral',  2,  '["Workers","Migration","Developer Experience"]',         1),
('forum',   'assets_help',  'How to serve static assets from Workers without using Pages? Documentation suggests the assets binding but there are very few working examples.',                                                               '2026-04-27T12:00:00Z', 'neutral',  4,  '["Workers","Static Assets","Documentation"]',            1),
('forum',   'json_pain',    'Workers AI Llama model gives inconsistent JSON outputs even with explicit prompting. Sometimes adds markdown fences, sometimes does not. Anyone have a reliable prompting strategy?',                          '2026-04-28T09:00:00Z', 'negative', 6,  '["Workers AI","LLM","JSON Parsing"]',                   1),
('forum',   'workflows_win','Finally got Cloudflare Workflows working after 2 days of debugging. Key insight nobody documents: each step return value MUST be JSON-serializable. Returning a D1 result object directly silently fails.',    '2026-04-29T14:45:00Z', 'neutral',  3,  '["Workflows","Documentation","D1"]',                    1);
